apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: qdnqn
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: App of apps qdnqn GitOps demo example.
  destinations:
    - server: https://kubernetes.default.svc
      name: in-cluster
      namespace: argocd
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'